steps:
# Build the container image and deploy to Cloud Run
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/nutrition-backend', './backend']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/nutrition-backend']

# Deploy container image to Cloud Run with database secret
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'nutrition-backend'
  - '--image'
  - 'gcr.io/$PROJECT_ID/nutrition-backend'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'DATABASE_URL=postgresql://postgres:post123!@34.68.199.158:5432/nutrition_db'
  - '--cpu'
  - '1'
  - '--memory'
  - '512Mi'
  - '--timeout'
  - '300'
  - '--min-instances'
  - '1'
  - '--port'
  - '8080'

images:
- 'gcr.io/$PROJECT_ID/nutrition-backend'

options:
  logging: CLOUD_LOGGING_ONLY 